baseURL: /
languageCode: en-us
publishDir: public/
canonifyURLs: true
title: guac
theme: hugo-fresh
googleAnalytics: G-C86QDTQNRG
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/guac-logo-squareish.png
    link: /
    text: GUAC
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Know your software supply chain
    # Hero subtitle (optional)
    subtitle: hero-some-subtitle-text
    # Button text
    button1text: Learn more
    button1link: "#about-guac"
    button2text: Github
    button2link: "https://github.com/guacsec/guac"

    # Hero image (from static/images/___)
    #image: illustrations/worker.svg
    image: logos/guac-logo.png


    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: FAQ
    url: /faq
  - title: Community
    url: /community
  - title: Docs
    url: https://guacsec.github.io/guac-docs
  - title: Github
    url: https://github.com/guacsec/guac
    button: true


  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # - title: Log in
  #   url: /
  # - title: Sign up
  #   url: /
  #   button: true
  #sidebar:
  #  # Logo (from /images/logos/___.svg)
  #  logo: fresh-square
  #  sections:
  #  - title: User
  #    icon: user
  #    links:
  #    - text: Profile
  #      url: /
  #    - text: Account
  #      url: /
  #    - text: Settings
  #      url: /
  #  - title: Messages
  #    icon: envelope
  #    links:
  #    - text: Inbox
  #      url: /
  #    - text: Compose
  #      url: /
  #  - title: Images
  #    icon: image
  #    links:
  #    - text: Library
  #      url: /
  #    - text: Upload
  #      url: /
  #  - title: Settings
  #    icon: cog
  #    links:
  #    - text: User settings
  #      url: /
  #    - text: App settings
  #      url: /
  section1:
    title: section1-text
    subtitle: section1-subtitle  guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac
    tiles:
    - title: s1-title-1
      icon: mouse-globe
      text:  guac guac guac guac  guac guac guac guac  guac guac guac guac  guac guac guac guac
      url: https://github.com/guacsec/guac
      buttonText: Find GUAC
    - title: s1-title-2
      icon: laptop-cloud
      text: Learn how to configure your existing organization to use GUAC
      url: https://github.com/guacsec/guac
      buttonText: Get GUAC
    - title: s1-title-3
      icon: plug-cloud
      text: See what can GUAC GUAC 
      url: https://github.com/guacsec/guac
      buttonText: Eat GUAC



  section2:
    title: What is GUAC?
    subtitle: section2-subtitle
    features:
    - title: Feature1 text
      text: Feature1-text guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Feature2 title
      text: Feature2-text guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac
      icon: plug-cloud
    - title: Feature3 title
      text: Feature3-text guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac
      icon: doc-sync


  sectionGithub:
    title: What's next?
    subtitle: Learn more about GUAC
    button1Text: Github
    button1Link: https://github.com/guacsec/guac
    button2Text: FAQ
    button2Link: /faq

  sectionUniid:
    title: GUAC chips today
    subtitle: section-uniid-demo demo demo our guac guac today....  guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac guac
    buttonText: Check out our demos
    buttonLink: "https://github.com/guacsec/guac"


  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3

  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
